<?php
/**
 * Clementine Theme Configuration
 *
 * This file sets up the theme's environment variables and registers theme support.
 * It also enqueues scripts and styles, and handles asset resolution for development and production environments.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package clementine
 * @since   1.0
 */

/*
 * These variables are used to define the theme's root, path, URI, and asset paths.
 *
 * CLEMENTINE_WEB_ROOT: /var/www/html/public
 * CLEMENTINE_ROOT: wp-content/themes/clementine
 * CLEMENTINE_PATH: /var/www/html/public/wp-content/themes/clementine
 * CLEMENTINE_URI: http://localhost:8080/wp-content/themes/clementine
 * CLEMENTINE_HMR_HOST: http://localhost:5173
 * CLEMENTINE_HMR_URI: http://localhost:5173/wp-content/themes/clementine
 * CLEMENTINE_ASSETS_PATH: /var/www/html/wp-content/themes/clementine/dist
 * CLEMENTINE_ASSETS_URI: http://localhost:8080/wp-content/themes/clementine/dist
 */

define( 'CLEMENTINE_WEB_ROOT', dirname( ABSPATH ) );
define( 'CLEMENTINE_ROOT', str_replace( CLEMENTINE_WEB_ROOT, '', get_template_directory() ) );
define( 'CLEMENTINE_PATH', CLEMENTINE_WEB_ROOT . CLEMENTINE_ROOT  );
define( 'CLEMENTINE_URI', get_template_directory_uri() );
define( 'CLEMENTINE_HMR_HOST', 'http://localhost:5173' );
define( 'CLEMENTINE_HMR_URI', CLEMENTINE_HMR_HOST . CLEMENTINE_ROOT );
define( 'CLEMENTINE_ASSETS_PATH', CLEMENTINE_PATH . '/dist' );
define( 'CLEMENTINE_ASSETS_URI', CLEMENTINE_URI . '/dist' );

/**
 * Sets up theme defaults and registers support for various WordPress features.
 *
 * Note that this function is hooked into the after_setup_theme hook, which
 * runs before the init hook. The init hook is too late for some features, such
 * as indicating support for post thumbnails.
 */
function clementine_setup_theme_support() {
	/*
		* Let WordPress manage the document title.
		* By adding theme support, we declare that this theme does not use a
		* hard-coded <title> tag in the document head, and expect WordPress to
		* provide it for us.
		*/
	add_theme_support( 'title-tag' );

	/*
		* Add support for post thumbnails on posts and pages.
		*/
	add_theme_support( 'post-thumbnails' );

	/*
		* Register navigation menu locations.
		*   - The 'navbar' location is used in the header.php file to display the primary menu.
		*   - The 'footer' location is not used yet!
		*/
	register_nav_menus(
		array(
			'navbar' => esc_html__( 'navbar', 'clementine' ),
			'footer' => esc_html__( 'footer', 'clementine' ),
		)
	);
}
add_action( 'after_setup_theme', 'clementine_setup_theme_support' );


/**
 * Resolves the URI for an asset based on the provided path using the manifest file.
 *
 * This function reads the asset manifest file to determine the correct URI for a given asset path.
 * In development environments, it returns the Hot Module Replacement (HMR) URI for live reloading.
 * In other environments, it returns the production asset URI.
 *
 * @param  string $path The asset path key to resolve from the manifest.
 * @return string The resolved asset URI, or an empty string if not found or on error.
 */
function clementine_resolve_url( string $path ): string {
	static $manifest = null;
	$manifest_path   = CLEMENTINE_ASSETS_PATH . '/manifest.json';

	if ( null === $manifest ) {
		if ( ! file_exists( $manifest_path ) ) {
			return '';
		}

        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		$manifest = json_decode( file_get_contents( $manifest_path ), true );
	}

	// If the manifest is not an array or does not contain the requested path, return an error.
	if ( ! is_array( $manifest ) || ! isset( $manifest[ $path ] ) ) {
		wp_die(
			esc_html(
				"Error: the asset '{$path}' was not found in the manifest.\n" .
				"This usually means the asset path is incorrect or the manifest is outdated.\n" .
				'Try running `npm run build` to regenerate the manifest, or check the asset path.'
			)
		);
	}

	/*
		Returns the correct URI for a requested asset by looking for either a 'src' or 'source' key
		in the manifest. If neither is found, it returns an empty string.
	*/
	if ( 'development' === WP_ENVIRONMENT_TYPE ) {
		// Check for 'src' key (generated by rollup).
		if ( isset( $manifest[ $path ]['src'] ) ) {
			return CLEMENTINE_HMR_URI . '/' . $manifest[ $path ]['src'];
		}
		// Check for 'source' key (generated by copy.js plugin).
		if ( isset( $manifest[ $path ]['source'] ) ) {
			return CLEMENTINE_HMR_URI . '/' . $manifest[ $path ]['source'];
		}
		// If neither key is found, return an empty string.
		return '';
	} else {
		return CLEMENTINE_ASSETS_URI . '/' . $manifest[ $path ]['file'];
	}
}


/**
 * Enqueue scripts and styles that gets generated by Vite.
 *
 * @package clementine
 * @since   1.0
 */
function clementine_enqueue_scripts() {

	$clementine_version = '1.0.0';

	if ( 'development' !== WP_ENVIRONMENT_TYPE ) {
		$clementine_version = filemtime( CLEMENTINE_ASSETS_PATH . '/manifest.json' ) ;	
	}

	wp_enqueue_script( 'clementine-scripts', clementine_resolve_url( 'src/scripts/main.js' ) , array(), $clementine_version, true );
	wp_enqueue_style( 'clementine-style', clementine_resolve_url( 'src/styles/main.scss' ), array(), $clementine_version );	

}
add_action( 'wp_enqueue_scripts', 'clementine_enqueue_scripts' );


/**
 * Appends the type="module" attribute that are enqued by the
 * clementine_enqueue_scripts function.
 *
 * @param  string $tag    The HTML script tag as a string.
 * @param  string $handle The script's handle or identifier.
 * @param  string $url    The script's source URL.
 * @return string The modified HTML <script> tag.
 */
function clementine_append_module_to_script( string $tag, string $handle, string $url ): string {
	// Check if the URL contains the HMR host or assets URI.
	if ( ( false !== strpos( $url, CLEMENTINE_HMR_HOST ) ) || ( false !== strpos( $url, CLEMENTINE_ASSETS_URI ) ) ) {
		$tag = str_replace( '<script ', '<script type="module" ', $tag );
	}

	return $tag;
}
add_action( 'script_loader_tag', 'clementine_append_module_to_script', 1, 3 );


/**
 * This script is necessary for enabling Hot Module Replacement (HMR) as
 * it outputs the Vite client script in the head of the document during development.
 *
 * @see https://vitejs.dev/guide/features.html#hot-module-replacement
 */
function clementine_enqueue_vite_client_script() {
	if ( 'development' === WP_ENVIRONMENT_TYPE ) {
        // phpcs:ignore WordPress.WP.EnqueuedResources.NonEnqueuedScript
		printf( '<script type="module" src="%s"></script>', esc_attr( CLEMENTINE_HMR_URI . '/@vite/client' ) );
	}
}
add_action( 'wp_head', 'clementine_enqueue_vite_client_script', 1, 0 );
