<?php
// File: wpstarter-extension/Steps/PublicHtaccessStep.php
// https://github.com/wecodemore/wpstarter/blob/3.0.0-beta.13/docs/08-Custom-Steps-Development.md

namespace WpStarterExtension\Steps;

use WeCodeMore\WpStarter\Step\FileCreationStepInterface;
use WeCodeMore\WpStarter\Step\Step;
use WeCodeMore\WpStarter\Config\Config;
use WeCodeMore\WpStarter\Util\Paths;
use WeCodeMore\WpStarter\Util\Locator;

/**
 * Class PublicHtaccessStep
 * This class implements a custom step to create a public .htaccess file for the public folder.
 */
class PublicHtaccessStep implements FileCreationStepInterface {

    private $filesystem;
    private $composerFilesystem;

    public function __construct(Locator $locator) 
    {
        $this->filesystem = $locator->filesystem();
        $this->composerFilesystem = $locator->composerFilesystem();
    }
    
    public function name(): string
    {
        return 'build-public-htaccess';
    }
    
    public function success(): string
    {
        return '<comment>public/.htaccess</comment> saved successfully.';
    }
    
    public function error(): string
    {
        return 'creation of public/.htaccess failed.';
    }
    
    public function targetPath(Paths $paths): string
    {
        return $paths->wpParent() . DIRECTORY_SEPARATOR . '.htaccess';
    }
    
    public function allowed(Config $config, Paths $paths): bool
    {
        return true;
    }
    
    public function run(Config $config, Paths $paths): int
    {
        // Get the target path for the .htaccess file
        $target = $this->targetPath($paths);

        // Ensure the target directory exists
        if ( file_exists($target) ) {
            // If the file already exists, we do not overwrite it
            // This is to prevent overwriting the existing .htaccess file
            return Step::SUCCESS;
        }

        // Get relative path using composer's findShortestPath 
        $from = $paths->wpParent('/');
        $to = $paths->wp('/');
        $relative = $from === $to
            ? ''
            : $this->composerFilesystem->findShortestPath($from, $to, true);

        // Get the content from the private function below
        $content = $this->fileContent($relative);

        // Save the content to the target path using the provided filesystem from the locator
        if ( $this->filesystem->save( $content, $target ) ) {
            return Step::SUCCESS;
        }
            
        return Step::ERROR; 
    }

    /**
     * Returns the content for the README.md file.
     *
     * @return string The content to be written to the README.md file inside the public folder.
     */
    private function fileContent(string $relative): string
    {
        $introduction = "# This .htaccess content is auto-generated by the WpStarterExtension.
# It handles WordPress permalinks and routes requests correctly,
# especially when WordPress core is in a subdirectory called /wp.\n\n";

       // Standard .htaccess rules that are always present
        $baseRules = <<<'HTACCESS_START'
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]
HTACCESS_START;

        // Rules specifically for WordPress installed in the '/wp' subdirectory
        $subdirectorySpecificRules = '';
        if ($relative) {
            // These sprintf calls inject the $relative path '/wp' into the rules.
            // %s is the placeholder for the $relative path.
            // $1 refers to the first capturing group of the RewriteRule's regex.
            $subdirectorySpecificRules .= sprintf(
                "\n" . "    RewriteRule ^(wp-(content|admin|includes).*) %s/$1 [L]\n",
                $relative
            );
            $subdirectorySpecificRules .= sprintf(
                "    RewriteRule ^(.*\.php)$ %s/$1 [L]\n",
                $relative
            );
        }

        // Final WordPress front-controller rule and closing tag
        $finalRules = <<<'HTACCESS_END'
    RewriteRule . index.php [L]
</IfModule>
HTACCESS_END;

        // Concatenating all parts to form the complete .htaccess content.
        return $introduction . $baseRules . $subdirectorySpecificRules . $finalRules;
    }
}