<?php
// File: wpstarter-extension/Steps/PublicReadmeStep.php
// https://github.com/wecodemore/wpstarter/blob/3.0.0-beta.13/docs/08-Custom-Steps-Development.md

namespace WpStarterExtension\Steps;

use WeCodeMore\WpStarter\Step\FileCreationStepInterface;
use WeCodeMore\WpStarter\Step\Step;
use WeCodeMore\WpStarter\Config\Config;
use WeCodeMore\WpStarter\Util\Paths;
use WeCodeMore\WpStarter\Util\Locator;

/**
 * Class PublicReadmeStep
 * This class implements a custom step to create a public README.md file for the public folder.
 */
class PublicReadmeStep implements FileCreationStepInterface {

    private $filesystem;

    public function __construct(Locator $locator) 
    {
        $this->filesystem = $locator->filesystem();
    }
    
    public function name(): string
    {
        return 'build-public-readme';
    }
    
    public function success(): string
    {
        return '<comment>public/README.md</comment> saved successfully.';
    }
    
    public function error(): string
    {
        return 'creation of public/README.md failed.';
    }
    
    public function targetPath(Paths $paths): string
    {
        return $paths->wpParent() . DIRECTORY_SEPARATOR . 'README.md';
    }
    
    public function allowed(Config $config, Paths $paths): bool
    {
        return true;
    }
    
    public function run(Config $config, Paths $paths): int
    {
        // Get the target path for the README.md file
        $target = $this->targetPath($paths);

         // Ensure the target directory exists
        if ( file_exists( $target ) ) {
            // If the file already exists, we do not overwrite it
            // This is to prevent overwriting the existing README.md file
            return Step::SUCCESS;
        }

        // Get the content from the private method below
        $content = $this->fileContent();

        // Save the content to the target path using the provided filesystem from the locator
        if ( $this->filesystem->save( $content, $target ) ) {
            return Step::SUCCESS;
        }
            
        return Step::ERROR; 
    }

    /**
     * Returns the content for the README.md file.
     *
     * @return string The content to be written to the README.md file inside the public folder.
     */
    private function fileContent(): string 
    {
        $content = <<<'README'
           
# Public Directory

This directory (`public/`) serves as the web root. All files and assets accessible via the web server are located here.

## ⚠️ Important: Managed by WP Starter

This folder is **automatically managed** by [WP Starter](https://wecodemore.github.io/wpstarter/) and Composer. Many files in this directory are generated or updated during the build process. **Do not manually edit, delete, or add files here unless you are certain of what you are doing.** and instead use `content/` to update your theme or plugin as the `public/` folder is not tracked by git!

## How this folder is structured

- **WordPress Core**: The `wp/` subdirectory contains WordPress core files, installed and updated via Composer.
- **wp-content**: The `wp-content/` directory in `public/` is symlinked to your project's `content/` folder.  
*Note: `public/wp-content/` may appear empty, but it points to your actual themes, plugins, and other content in `content/`.* More information can be found [here](wpstarter-extension%5CREADME.md) 
- **Configuration Files**:
- `wp-config.php` is auto-generated by WP Starter ([docs](https://wecodemore.github.io/wpstarter/03-WordPress-Integration.html#wp-starter-wp-config-interactions)).
- `.htaccess` and `README.md` are auto-generated by custom steps in `wpstarter-extension/` to handle routing and documentation.  
    *You can safely modify `.htaccess` and `README.md`; they will not be overwritten unless deleted. For consistency, update the corresponding step if you want changes to persist for all contributors.*
- **Git**: The `public/` folder is not tracked by Git. Manage your code and assets in `content/` and let WP Starter handle the build process.


## Safe Customization

- **If you need to customize** `.htaccess` or `wp-config.php` or add/remove, do so by extending the WP Starter templates or through custom steps--**preferably not by editing the files directly in this folder**. Although `.htaccess` and README.md will not be overwritten if changed, it’s recommended to update the corresponding WP Starter step so other contributors receive the same rules or description.
- **Never add custom files** here unless you understand the WP Starter workflow and are prepared for your changes to be overwritten.

---

> **This folder is intended for web server access only. All source code, themes, plugins, and configuration should be managed outside of `public/` and brought in via Composer and WP Starter.**
README;

        return $content;
    }
}